/**
 * content/cities.js — Données des villes pour les pages SEO locales.
 *
 * Chaque entrée doit avoir un contenu UNIQUE (Google sanctionne le duplicate
 * content). On personnalise : description contexte yoga local, lieux connus,
 * stats, citation type.
 *
 * Pour ajouter une ville : copier un objet, adapter, créer une route
 * app/prof-yoga-[slug]/page.js qui importe l'objet et passe à LocalLanding.
 */

export const CITIES = {
  paris: {
    name: 'Paris',
    region: 'Île-de-France',
    slug: 'paris',
    codePostal: '75',
    profDescription: `Paris concentre la plus grande densité de profs de yoga indépendant·e·s en France : plus de 800 profs actifs·ves recensés en 2025, répartis entre les studios Marais, Bastille, Pigalle, Le Marais, et les nombreuses salles louées dans les 11e, 12e, 18e et 19e arrondissements. La pratique parisienne se distingue par sa diversité — du Vinyasa rapide compatible avec les pauses déjeuner des actifs aux retraites Yin du week-end, en passant par les ateliers de Pilates Reformer haut de gamme. Le défi local : un loyer de salle à l'heure parmi les plus élevés d'Europe (40-100 €/h), qui pousse les profs solo à optimiser leur taux de remplissage au maximum.`,
    lieuxConnus: [
      'Le Tigre Yoga Club',
      'Yoga Village',
      'Casa Yoga',
      'Rasa Yoga Rive Gauche',
      'Yuj Studio',
      'Affinity Yoga',
      'Trini Yoga',
      'Maison Sur Soi',
      'Studio Carre Yoga',
      'Sources & Visions',
    ],
    stats: [
      { value: '800+', label: 'Profs yoga indépendant·e·s recensé·e·s à Paris' },
      { value: '40-100 €', label: "Tarif horaire moyen de location de salle" },
      { value: '17-22 €', label: 'Tarif moyen par cours collectif' },
      { value: '12-16', label: 'Cours hebdo médian par prof confirmée' },
    ],
    citation: {
      text: "À Paris, le yoga n'est plus un luxe — c'est devenu une infrastructure mentale pour beaucoup de gens qui télétravaillent et qui veulent un ancrage régulier dans leur semaine.",
      author: 'Maude · prof de yoga, Paris 11e',
    },
    pilates: {
      profDescription: `Paris a le marché Pilates le plus dense et le plus segmenté de France. Trois sous-segments cohabitent : (1) le Pilates Mat traditionnel issu de la méthode Joseph Pilates, dispensé majoritairement par d'ancien·ne·s danseuses et kinés ; (2) le Pilates Reformer haut de gamme dans des studios spécialisés (10-15 k€ d'investissement matériel par studio) avec une clientèle premium ; (3) le Pilates Clinical (kinés-Pilates) pour la rééducation post-traumatique. Les quartiers concentrant les studios : Marais, Bastille, Trocadéro, 16ᵉ, 7ᵉ. Loyer salle 50-90 €/h pour location standard, 70-130 €/h pour studio équipé Reformer. Cours collectif Mat : 22-30 €, cours collectif Reformer : 35-55 €, 1-à-1 Reformer : 80-150 €.`,
      lieuxConnus: [
        'Pilates ProWorks Paris',
        'Studio Reformer Paris',
        'Pure Pilates Paris',
        'Pilates Bastille',
        'Mat Pilates Marais',
        'Stott Pilates Paris 16',
        'Pilates Clinique Paris',
        'Reformer Studio Trocadéro',
        'Pilates Loft Paris',
        'Body Mind Paris',
      ],
      stats: [
        { value: '200+', label: 'Studios Pilates spécialisés à Paris' },
        { value: '50-130 €', label: 'Tarif horaire location salle (Mat / Reformer)' },
        { value: '22-55 €', label: 'Tarif cours collectif (Mat / Reformer)' },
        { value: '10-14', label: 'Cours hebdo médian par prof confirmée' },
      ],
      citation: {
        text: "À Paris, le Reformer a complètement changé la donne. Les élèves comprennent qu'on offre quelque chose qu'un cours collectif classique ne peut pas — un travail précis, sur-mesure, avec une vraie progression mesurable.",
        author: 'Sophie · prof Pilates Reformer, Paris 11e',
      },
    },
  },

  lyon: {
    name: 'Lyon',
    region: 'Auvergne-Rhône-Alpes',
    slug: 'lyon',
    codePostal: '69',
    profDescription: `Lyon est devenue ces 5 dernières années l'un des hubs yoga les plus dynamiques de France après Paris. Le quartier de la Croix-Rousse, la Presqu'île et le 7e arrondissement concentrent la majorité des studios indépendants. La scène lyonnaise se caractérise par une forte présence du Hatha traditionnel, du Yin, et une vraie demande pour les formats "doux" (prénatal, postnatal, yoga seniors). Avantage notable par rapport à Paris : des loyers de salle 30-40 % moins élevés (typiquement 20-50 €/h), ce qui permet aux profs solo de tenir avec moins d'élèves par cours et de dégager une rentabilité plus rapidement.`,
    lieuxConnus: [
      'Centre de Yoga Iyengar Lyon',
      'Sukha Yoga',
      'Le Yoga Studio',
      'Yoga Croix-Rousse',
      'Yoga Lounge',
      'Studio Hridaya',
      'Atelier Soleil',
      'Yoga Citta',
      'Méluna Yoga',
      'Asana Studio Lyon',
    ],
    stats: [
      { value: '250+', label: 'Profs yoga indépendant·e·s recensé·e·s à Lyon' },
      { value: '20-50 €', label: "Tarif horaire moyen de location de salle" },
      { value: '14-18 €', label: 'Tarif moyen par cours collectif' },
      { value: '10-14', label: 'Cours hebdo médian par prof confirmée' },
    ],
    citation: {
      text: "Lyon a la chance d'avoir une vraie scène locale soudée. Les profs se connaissent, se recommandent, organisent des retraites communes — c'est un écosystème, pas une compétition.",
      author: 'Solène · prof de yoga, Lyon Croix-Rousse',
    },
    pilates: {
      profDescription: `Lyon a vu sa scène Pilates exploser depuis 5 ans, portée notamment par des profs venues du yoga ou de la danse classique. Le Pilates Mat domine encore largement (~75 % de l'offre), mais le Reformer prend du terrain — surtout dans le 6ᵉ arrondissement et la Croix-Rousse où plusieurs studios spécialisés ont ouvert. La clientèle lyonnaise est plus sensible au rapport qualité-prix que la clientèle parisienne : les studios qui marchent sont ceux qui proposent du Reformer à un tarif accessible (35-50 €/cours collectif), pas du premium ultra-cher. Beaucoup de profs lyonnaises combinent Pilates avec une autre discipline (yoga, sophro, danse) pour diversifier leur planning et leurs revenus.`,
      lieuxConnus: [
        'Pilates Studio Lyon',
        'Reformer Lyon',
        'Pure Pilates Lyon',
        'Pilates Croix-Rousse',
        'Mat Studio Lyon',
        'Méthode Pilates Lyon',
        'Pilates 6e',
        'Studio Pilates Confluence',
        'Pilates Vaise',
        'Pilates Lyon Centre',
      ],
      stats: [
        { value: '100+', label: 'Studios/profs Pilates indé à Lyon' },
        { value: '30-70 €', label: 'Tarif horaire location salle (Mat / Reformer)' },
        { value: '16-25 €', label: 'Tarif cours collectif Mat' },
        { value: '35-50 €', label: 'Tarif cours collectif Reformer' },
      ],
      citation: {
        text: "À Lyon, l'élève Pilates est plus exigeante qu'en yoga — elle veut sentir un vrai travail technique. Tu peux pas te contenter d'animer, tu dois enseigner précisément. Et le bouche-à-oreille est implacable.",
        author: 'Manon · prof Pilates, Lyon 6e',
      },
    },
  },

  bordeaux: {
    name: 'Bordeaux',
    region: 'Nouvelle-Aquitaine',
    slug: 'bordeaux',
    codePostal: '33',
    profDescription: `Bordeaux a vu sa scène yoga exploser depuis l'arrivée de la LGV en 2017 — beaucoup de profs parisien·ne·s s'y sont installé·e·s, attiré·e·s par un cadre de vie plus calme et des loyers de salle deux fois moins élevés (22-50 €/h en moyenne). Les Chartrons, Saint-Pierre et la rive droite (La Bastide) concentrent l'essentiel des studios indépendants. Particularité bordelaise : une vraie tradition d'ateliers "yoga & vin" ou "yoga & œnologie" qui colle au territoire, et beaucoup de profs qui proposent des retraites week-end dans le Médoc ou le Bassin d'Arcachon. La pratique dominante reste le Vinyasa et le Hatha, avec une demande croissante pour le Yin et le yoga prénatal.`,
    lieuxConnus: [
      'Yoga Inside Bordeaux',
      'La Yoga Boutique',
      'Sukha Yoga Bordeaux',
      'Vinyasa Yoga Bordeaux',
      'ON Yoga',
      'Yoga Lifestyle Bordeaux',
      'Chartrons Yoga',
      'Studio Sangha',
      'Yoga Bordeaux Centre',
      'Atelier Pranayama',
    ],
    stats: [
      { value: '150+', label: 'Profs yoga indépendant·e·s recensé·e·s à Bordeaux' },
      { value: '22-50 €', label: 'Tarif horaire moyen de location de salle' },
      { value: '13-17 €', label: 'Tarif moyen par cours collectif' },
      { value: '8-12', label: 'Cours hebdo médian par prof confirmée' },
    ],
    citation: {
      text: "À Bordeaux, on a le luxe d'un vrai art de vivre. Mes élèves viennent pour la pratique, mais aussi pour ce qui se passe avant et après — un café, un échange, un week-end dans le Médoc.",
      author: 'Camille · prof de yoga, Bordeaux Chartrons',
    },
    pilates: {
      profDescription: `Bordeaux a vu sa scène Pilates suivre l'attraction parisienne post-LGV : plusieurs profs Pilates confirmées sont arrivées de Paris ces 5 dernières années avec une expertise Reformer, ce qui a complètement structuré l'offre locale. Aujourd'hui, Bordeaux est probablement la 3ᵉ ville française pour le Pilates Reformer après Paris et Lyon. Quartiers les plus actifs : Chartrons (zone bobo premium), Saint-Pierre, et la rive droite émergente. Tarifs intermédiaires entre Paris et Toulouse (Mat 16-22 €, Reformer 35-55 €). Particularité bordelaise : plusieurs studios combinent Pilates Reformer avec des modalités SPA (sauna, hammam, soins) pour un positionnement très premium.`,
      lieuxConnus: [
        'Pilates Studio Bordeaux',
        'Reformer Bordeaux',
        'Pure Pilates Bordeaux',
        'Pilates Chartrons',
        'Mat Studio Bordeaux',
        'Pilates Saint-Pierre',
        'Stott Pilates Bordeaux',
        'Pilates Bordeaux Centre',
        'Pilates La Bastide',
        'Reformer Studio Caudéran',
      ],
      stats: [
        { value: '100+', label: 'Studios/profs Pilates indé à Bordeaux' },
        { value: '28-65 €', label: 'Tarif horaire location salle' },
        { value: '16-22 €', label: 'Tarif cours collectif Mat' },
        { value: '35-55 €', label: 'Tarif cours collectif Reformer' },
      ],
      citation: {
        text: "Bordeaux est la ville idéale pour démarrer un studio Pilates : assez de demande premium, des tarifs immobiliers tenables, et une clientèle qui prend le temps de comprendre la méthode. Tout l'inverse de Paris.",
        author: 'Charlotte · prof Pilates Reformer, Bordeaux Chartrons',
      },
    },
  },

  marseille: {
    name: 'Marseille',
    region: "Provence-Alpes-Côte d'Azur",
    slug: 'marseille',
    codePostal: '13',
    profDescription: `Marseille a la scène yoga la plus singulière de France : ici, on pratique dehors une bonne partie de l'année. Beaucoup de profs proposent des cours réguliers dans les calanques (Sormiou, Morgiou), sur la plage de la Pointe-Rouge ou dans les parcs (Borély, Longchamp). La Plaine, Vauban, les Cinq-Avenues et Castellane regroupent la majorité des studios couverts. La pratique dominante est un Vinyasa très solaire, doublé d'une vraie demande pour les retraites week-end dans le Luberon ou sur les îles du Frioul. Les loyers de salle sont restés modérés (25-55 €/h) malgré la popularité grandissante de la ville auprès des Parisien·ne·s.`,
    lieuxConnus: [
      'Yoga Marseille Centre',
      'Casa Yoga Marseille',
      "Atelier du Souffle",
      'Yoga Sud',
      "Centre de Yoga Iyengar Marseille",
      "Yoga Bel-Air",
      "Studio Hridaya Marseille",
      "Yoga'ttitude",
      "Marseille Yoga Studio",
      "Pranayoga Marseille",
    ],
    stats: [
      { value: '200+', label: 'Profs yoga indépendant·e·s recensé·e·s à Marseille' },
      { value: '25-55 €', label: 'Tarif horaire moyen de location de salle' },
      { value: '13-18 €', label: 'Tarif moyen par cours collectif' },
      { value: '10-14', label: 'Cours hebdo médian par prof confirmée' },
    ],
    citation: {
      text: "Pratiquer face à la mer change tout. Mes élèves payent pour la séance, mais c'est ce qu'on ressent en sortant de l'eau après le savasana qui les ramène la semaine d'après.",
      author: 'Inès · prof de yoga, Marseille Cinq-Avenues',
    },
    pilates: {
      profDescription: `Marseille a une scène Pilates en pleine ascension, portée par la dimension "bien-être méditerranéen" très ancrée localement. Le Pilates Mat domine très largement, avec une croissance plus lente du Reformer qu'à Bordeaux ou Lyon. Le Reformer s'implante doucement dans le 8ᵉ (Pointe-Rouge, Bonneveine), Vauban et le centre. La spécificité marseillaise : forte demande pour le Pilates post-natal, en lien avec une population jeune en plein boom démographique. Beaucoup de profs proposent des formats "Pilates + sortie en mer kayak/SUP" pendant la belle saison. Tarifs très compétitifs (Mat 14-19 €, Reformer 30-45 € quand il existe).`,
      lieuxConnus: [
        'Pilates Marseille Centre',
        'Reformer Studio Marseille',
        'Pilates Bel-Air',
        'Mat Pilates Pointe-Rouge',
        'Studio Pilates Vauban',
        'Pilates Castellane',
        'Stott Pilates Marseille',
        'Pilates Bonneveine',
        'Reformer Marseille 8e',
        'Pilates La Plaine',
      ],
      stats: [
        { value: '120+', label: 'Studios/profs Pilates indé à Marseille' },
        { value: '25-65 €', label: 'Tarif horaire location salle' },
        { value: '14-19 €', label: 'Tarif cours collectif Mat' },
        { value: '30-45 €', label: 'Tarif cours collectif Reformer' },
      ],
      citation: {
        text: "Marseille a une vraie demande pour le Pilates post-natal — les jeunes mamans cherchent une remise en forme douce et progressive. C'est devenu mon créneau principal, avec des cours qui se remplissent en 48h dès l'annonce.",
        author: 'Léa · prof Pilates, Marseille Castellane',
      },
    },
  },

  toulouse: {
    name: 'Toulouse',
    region: 'Occitanie',
    slug: 'toulouse',
    codePostal: '31',
    profDescription: `Toulouse a une scène yoga jeune et universitaire, profondément marquée par la proximité culturelle avec l'Inde — plusieurs profs locales se sont formées à Mysore (Ashtanga) ou Rishikesh (Hatha traditionnel). Le Vinyasa et l'Ashtanga dominent, avec une bonne présence du Kundalini et du Yoga Nidra. Les quartiers de Carmes, Saint-Cyprien (rive gauche), Capitole et Compans-Caffarelli concentrent la majorité des studios. Particularité toulousaine : les tarifs sont restés parmi les plus accessibles de France (12-16 € par cours), pour rester en phase avec un public étudiant nombreux. Les loyers de salle suivent (20-45 €/h), ce qui rend la rentabilité plus rapide pour les profs solo.`,
    lieuxConnus: [
      'Yoga Toulouse',
      'La Maison du Yoga Toulouse',
      'Yoga Carmes',
      'Yoga Capitole',
      'Sukha Yoga Toulouse',
      'Ashtanga Yoga Toulouse',
      'Studio Hridaya Toulouse',
      'Atelier Pranava',
      'Hatha Yoga Toulouse',
      'Yoga Saint-Cyprien',
    ],
    stats: [
      { value: '150+', label: 'Profs yoga indépendant·e·s recensé·e·s à Toulouse' },
      { value: '20-45 €', label: 'Tarif horaire moyen de location de salle' },
      { value: '12-16 €', label: 'Tarif moyen par cours collectif' },
      { value: '12-16', label: 'Cours hebdo médian par prof confirmée' },
    ],
    citation: {
      text: "Toulouse a cette force d'avoir gardé des tarifs accessibles. Du coup les cours se remplissent vite, et tu peux vraiment vivre du yoga avec 12 cours par semaine — chose impossible à Paris ou Lyon au même prix.",
      author: 'Léa · prof de yoga, Toulouse Saint-Cyprien',
    },
    pilates: {
      profDescription: `Toulouse a une scène Pilates qui suit le pattern toulousain habituel : universitaire, accessible, et qualitative. Les tarifs sont parmi les plus bas de France (Mat 13-17 €, Reformer 28-40 € quand il existe). La majorité de l'offre est en Pilates Mat traditionnel, avec une montée en puissance du Pilates Clinical (kinés-Pilates) en lien avec les nombreux étudiants en kinésithérapie de la fac de médecine — c'est une vraie spécificité toulousaine. Quartiers : Carmes, Saint-Cyprien (rive gauche), Capitole, et Compans-Caffarelli côté nord. Les studios Reformer restent rares (3-4 sur toute la métropole) mais en croissance régulière.`,
      lieuxConnus: [
        'Pilates Studio Toulouse',
        'Reformer Toulouse',
        'Mat Studio Toulouse',
        'Pilates Carmes',
        'Studio Pilates Capitole',
        'Pilates Saint-Cyprien',
        'Pilates Clinical Toulouse',
        'Méthode Pilates Toulouse',
        'Pilates Compans',
        'Pilates Toulouse Sud',
      ],
      stats: [
        { value: '80+', label: 'Studios/profs Pilates indé à Toulouse' },
        { value: '22-55 €', label: 'Tarif horaire location salle' },
        { value: '13-17 €', label: 'Tarif cours collectif Mat' },
        { value: '28-40 €', label: 'Tarif cours collectif Reformer' },
      ],
      citation: {
        text: "Toulouse permet de proposer du Pilates accessible sans se brader. Notre clientèle étudiante et jeunes actives compose mes meilleurs cours — ils sont curieux, assidus, et reviennent semaine après semaine.",
        author: 'Camille · prof Pilates, Toulouse Saint-Cyprien',
      },
    },
  },

  nantes: {
    name: 'Nantes',
    region: 'Pays de la Loire',
    slug: 'nantes',
    codePostal: '44',
    profDescription: `Nantes a une scène yoga particulièrement créative, marquée par la culture alternative de la ville. On y trouve une vraie offre de yoga hybride — danse-yoga, acroyoga, yoga & sound healing, ateliers yoga-écriture — qu'on retrouve rarement ailleurs en France. Les quartiers de Bouffay (centre), de l'Île de Nantes (création contemporaine), des Hauts-Pavés et de Doulon concentrent les studios indépendants. Forte présence du yoga doux, prénatal et seniors, en cohérence avec une population de jeunes parents. Beaucoup de profs nantaises organisent des retraites week-end sur la côte (Pornic, Pornichet, Noirmoutier) ou en presqu'île de Guérande. Loyers de salle modérés (22-48 €/h).`,
    lieuxConnus: [
      'Yoga Nantes Centre',
      'La Maison du Yoga Nantes',
      'Yoga Bouffay',
      'Sukha Yoga Nantes',
      'Atelier du Yoga Nantes',
      'Studio Air Nantes',
      'Yoga & Vibes',
      'Centre de Yoga Iyengar Nantes',
      'Hatha Yoga Nantes',
      'Studio Hridaya Nantes',
    ],
    stats: [
      { value: '120+', label: 'Profs yoga indépendant·e·s recensé·e·s à Nantes' },
      { value: '22-48 €', label: 'Tarif horaire moyen de location de salle' },
      { value: '13-17 €', label: 'Tarif moyen par cours collectif' },
      { value: '9-13', label: 'Cours hebdo médian par prof confirmée' },
    ],
    citation: {
      text: "Nantes laisse beaucoup de place à l'expérimentation. J'ai pu lancer un format danse-yoga qui aurait été inaudible ailleurs — ici les élèves cherchent justement ce mélange.",
      author: 'Marion · prof de yoga, Nantes Bouffay',
    },
  },

  strasbourg: {
    name: 'Strasbourg',
    region: 'Grand Est',
    slug: 'strasbourg',
    codePostal: '67',
    profDescription: `Strasbourg a une scène yoga discrète mais très qualitative, marquée par sa position transfrontalière avec l'Allemagne. Influence forte de la pratique allemande (Iyengar rigoureux, Yin profond) qui se mêle à un Hatha plus traditionnel. Les quartiers de la Krutenau, Petite France et Neudorf concentrent l'essentiel des studios. Particularité strasbourgeoise : une partie des profs propose des cours bilingues français/allemand (clientèle fonctionnaires européens) et organise des retraites dans les Vosges et la Forêt-Noire toute proche. Loyers de salle modérés (22-50 €/h) avec des espaces souvent grands et lumineux hérités des bâtiments alsaciens.`,
    lieuxConnus: [
      'Yoga Strasbourg Krutenau',
      'Sukha Yoga Strasbourg',
      'Centre de Yoga Iyengar Strasbourg',
      'Studio Hridaya Strasbourg',
      'Yoga Studio Neudorf',
      'Atelier Soleil Strasbourg',
      'Hatha Yoga Strasbourg',
      'Yoga Petite France',
      'Méluna Yoga Strasbourg',
      'Yoga Méditation Strasbourg',
    ],
    stats: [
      { value: '120+', label: 'Profs yoga indépendant·e·s recensé·e·s à Strasbourg' },
      { value: '22-50 €', label: 'Tarif horaire moyen de location de salle' },
      { value: '13-17 €', label: 'Tarif moyen par cours collectif' },
      { value: '10-14', label: 'Cours hebdo médian par prof confirmée' },
    ],
    citation: {
      text: "À Strasbourg, on a la chance d'avoir un public exigeant et fidèle. La proximité avec l'Allemagne tire toute la scène vers le haut — on apprend vite que la rigueur paye.",
      author: 'Anne-Sophie · prof de yoga, Strasbourg Krutenau',
    },
  },

  lille: {
    name: 'Lille',
    region: 'Hauts-de-France',
    slug: 'lille',
    codePostal: '59',
    profDescription: `Lille a une scène yoga jeune et associative, fortement ancrée dans le tissu étudiant local. Les quartiers de Wazemmes, du Vieux-Lille, de Vauban et de Saint-Maurice concentrent l'essentiel des studios. Caractéristique lilloise : un vrai croisement disciplinaire entre yoga, danse contemporaine et théâtre — on y trouve plus de profs proposant des formats hybrides (yoga-écriture, yoga-danse, ateliers performatifs) qu'ailleurs en France. La proximité de la Belgique amène aussi une clientèle binationale. Loyers de salle parmi les plus accessibles des grandes villes (20-45 €/h) — un vrai avantage pour les profs qui démarrent. Forte demande sur le yoga doux et prénatal en lien avec une population jeune en âge d'avoir des enfants.`,
    lieuxConnus: [
      'Yoga Lille Centre',
      'La Maison du Yoga Lille',
      'Yoga Wazemmes',
      'Atelier du Yoga Lille',
      'Studio Hridaya Lille',
      'Sukha Yoga Lille',
      'Yoga Lille Sud',
      'Hatha Yoga Lille',
      'Yoga Studio Vieux Lille',
      'Méluna Yoga Lille',
    ],
    stats: [
      { value: '110+', label: 'Profs yoga indépendant·e·s recensé·e·s à Lille' },
      { value: '20-45 €', label: 'Tarif horaire moyen de location de salle' },
      { value: '12-16 €', label: 'Tarif moyen par cours collectif' },
      { value: '10-14', label: 'Cours hebdo médian par prof confirmée' },
    ],
    citation: {
      text: "Lille a cette énergie associative qui change tout. Les profs s'entraident, échangent leurs salles, partagent leurs élèves quand ça déborde — j'ai jamais vu un tel esprit collectif ailleurs.",
      author: 'Pauline · prof de yoga, Lille Wazemmes',
    },
  },

  montpellier: {
    name: 'Montpellier',
    region: 'Occitanie',
    slug: 'montpellier',
    codePostal: '34',
    profDescription: `Montpellier connaît une expansion yoga spectaculaire depuis l'afflux post-2020 de Parisien·ne·s en télétravail. La ville cumule trois avantages rares : un public jeune et bien formé (4ᵉ ville étudiante de France), un climat qui permet la pratique en extérieur 9 mois sur 12, et la mer à 10 minutes — beaucoup de profs proposent des cours sur la plage de Palavas l'été. L'Écusson, Beaux-Arts, Antigone et le quartier des Comédies concentrent les studios. Pratiques dominantes : Vinyasa solaire, Yin et yoga prénatal/postnatal (le public familial est important). Loyers de salle 22-50 €/h, en hausse marquée depuis 3 ans. La scène locale est très dynamique avec plusieurs retraites régulières en Cévennes et Pic Saint-Loup.`,
    lieuxConnus: [
      'Yoga Montpellier Écusson',
      'Sukha Yoga Montpellier',
      'Le Yoga Studio Montpellier',
      'Studio Hridaya Montpellier',
      'Casa Yoga Montpellier',
      'Yoga Beaux-Arts',
      'Centre de Yoga Iyengar Montpellier',
      'Hatha Yoga Montpellier',
      'Yoga Méditation Montpellier',
      'Atelier Pranava Montpellier',
    ],
    stats: [
      { value: '150+', label: 'Profs yoga indépendant·e·s recensé·e·s à Montpellier' },
      { value: '22-50 €', label: 'Tarif horaire moyen de location de salle' },
      { value: '13-17 €', label: 'Tarif moyen par cours collectif' },
      { value: '11-15', label: 'Cours hebdo médian par prof confirmée' },
    ],
    citation: {
      text: "Montpellier a complètement changé en 5 ans. On est passé d'une scène locale tranquille à un vrai pôle yoga du Sud, avec une clientèle qui sait ce qu'elle veut. C'est exigeant mais hyper stimulant.",
      author: 'Margaux · prof de yoga, Montpellier Beaux-Arts',
    },
  },

  rennes: {
    name: 'Rennes',
    region: 'Bretagne',
    slug: 'rennes',
    codePostal: '35',
    profDescription: `Rennes a une scène yoga marquée par la culture bretonne — proximité à la nature, à la mer (Saint-Malo à 50 km) et à une tradition wellness ancienne. Les quartiers du Centre, des Halles, de Sainte-Anne et de Beauregard concentrent les studios. Forte présence du yoga doux, du Hatha traditionnel et du Yin — moins de Vinyasa rapide qu'en région parisienne. Beaucoup de profs organisent des retraites week-end sur la côte sud bretonne (presqu'île de Quiberon, Belle-Île, golfe du Morbihan) — c'est devenu une vraie signature locale. Loyers de salle modérés (22-45 €/h). La population universitaire (2ᵉ pôle étudiant de France après Paris) alimente une demande constante en cours accessibles à tarif étudiant.`,
    lieuxConnus: [
      'Yoga Rennes Centre',
      'La Maison du Yoga Rennes',
      'Studio Hridaya Rennes',
      'Sukha Yoga Rennes',
      'Yoga Atalante',
      'Atelier du Yoga Rennes',
      'Yoga Rennes Sud',
      'Hatha Yoga Rennes',
      'Centre de Yoga Iyengar Rennes',
      'Yoga Studio Sainte-Anne',
    ],
    stats: [
      { value: '100+', label: 'Profs yoga indépendant·e·s recensé·e·s à Rennes' },
      { value: '22-45 €', label: 'Tarif horaire moyen de location de salle' },
      { value: '12-16 €', label: 'Tarif moyen par cours collectif' },
      { value: '9-13', label: 'Cours hebdo médian par prof confirmée' },
    ],
    citation: {
      text: "Ici, l'élève vient autant pour la séance que pour ce qu'il y a autour — la promenade vers le studio, le café après, et l'idée qu'on peut prolonger en week-end sur la côte. C'est tout un art de vivre.",
      author: 'Anaïs · prof de yoga, Rennes Sainte-Anne',
    },
  },

  nice: {
    name: 'Nice',
    region: "Provence-Alpes-Côte d'Azur",
    slug: 'nice',
    codePostal: '06',
    profDescription: `Nice a une scène yoga atypique en France, marquée par sa double dimension : public local fidèle ET clientèle internationale (résidents secondaires, expatriés, touristes longue durée). Cette mixité tire les tarifs vers le haut — les profs niçoises facturent typiquement 15-22 €/cours, parfois plus pour les formats premium. Les quartiers du Vieux Nice, du Carré d'Or, de Cimiez et de Riquier concentrent les studios. Particularité locale : de nombreux profs proposent des cours sur la Promenade des Anglais aux beaux jours, et des formats "yoga + chemins de l'arrière-pays" (Tourrettes, La Turbie). Loyers de salle 30-65 €/h selon zone — plutôt élevés dans les zones touristiques mais plus accessibles côté Saint-Roch ou Libération.`,
    lieuxConnus: [
      'Yoga Nice Centre',
      'Casa Yoga Nice',
      'Studio Hridaya Nice',
      'Sukha Yoga Nice',
      'Le Yoga Studio Nice',
      'Yoga Promenade Nice',
      'Centre de Yoga Iyengar Nice',
      'Yoga Vieux Nice',
      'Hatha Yoga Nice',
      'Atelier du Souffle Nice',
    ],
    stats: [
      { value: '140+', label: 'Profs yoga indépendant·e·s recensé·e·s à Nice' },
      { value: '30-65 €', label: 'Tarif horaire moyen de location de salle' },
      { value: '15-22 €', label: 'Tarif moyen par cours collectif' },
      { value: '10-14', label: 'Cours hebdo médian par prof confirmée' },
    ],
    citation: {
      text: "Niçoise et internationale à la fois, c'est ce qui rend la pratique ici particulière. Tu peux enseigner en français le matin et en anglais l'après-midi — et personne ne s'étonne. C'est unique en France.",
      author: 'Elena · prof de yoga, Nice Carré d\'Or',
    },
  },
};
